export enum Methods {
  selectWallet = "selectWallet",
  connectWallet = "connectWallet",
  getCurrentWallet = "getCurrentWallet",
  switchNetwork = "switchNetwork",
  sign = "sign",
  contractCall = "contractCall",
  createCapibility = "createCapibility",
  checkCapibility = "checkCapibility",
  getChainFromPkh = "getChainFromPkh",
  getPkhList = "getPkhList",
  getCurrentPkh = "getCurrentPkh",
  getWalletByPkh = "getWalletByPkh",
  createNewPkh = "createNewPkh",
  switchPkh = "switchPkh",

  getDAppTable = "getDAppTable",
  getDAppInfo = "getDAppInfo",
  getValidAppCaps = "getValidAppCaps",
  getModelBaseInfo = "getModelBaseInfo",

  loadStream = "loadStream",
  loadStreamsBy = "loadStreamsBy",
  createStream = "createStream",
  updateStream = "updateStream",

  readFolders = "readFolders",
  createFolder = "createFolder",
  updateFolderBaseInfo = "updateFolderBaseInfo",
  changeFolderType = "changeFolderType",
  deleteFolder = "deleteFolder",
  monetizeFolder = "monetizeFolder",

  uploadFile = "uploadFile",
  updateFileBaseInfo = "updateFileBaseInfo",
  moveFiles = "moveFiles",
  removeFiles = "removeFiles",
  monetizeFile = "monetizeFile",

  createProfile = "createProfile",
  getProfiles = "getProfiles",
  collect = "collect",
  isCollected = "isCollected",
  getDatatokenMetadata = "getDatatokenMetadata",
  unlock = "unlock",
}
